---

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 1:00 every day
    - cron: '0 1 * * *'

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.12"] # ["3.10", "3.11", "3.12"]
        platform: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # We do not use the cache action as uv is faster than the cache action.
      - name: "Install dependencies"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install --system --upgrade --editable .[dev]

      # - name: "Lint"
      #   run: |
      #     pre-commit run --all-files --hook-stage commit --verbose
      #     pre-commit run --all-files --hook-stage push --verbose
      #     pre-commit run --all-files --hook-stage manual --verbose

      - name: "Run tests"
        run: |
          pytest -s -vvv -x tests/test_shell_evaluator.py -k test_output_shown_on_error
